jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Runner Information
        run: |
          echo "Operating System: ${{ runner.os }}"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Runner Labels: ${{ runner.labels }}"

