name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Pas dit aan naar de naam van je hoofdtak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Pas dit aan naar de gewenste Ruby-versie

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          gem install bundler
          
      - name: Install Ruby and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install bundler      

      - name: Build and Deploy AmuseWiki
        run: |
          git clone https://github.com/melmothx/amusewiki.git
          cd amusewiki
          gem install bundler

      - name: Build and Deploy AmuseWiki
        run: |
          # Voeg hier instructies toe om AmuseWiki te bouwen en uit te rollen
          # Bijvoorbeeld:
          bundle exec rake assets:precompile
          bundle exec rake db:migrate
          bundle exec rails server -d  # Start de server in de achtergrond


      # Voeg hier stappen toe voor monitoring, bijvoorbeeld het opzetten van Prometheus en Grafana

      # Voeg hier stappen toe voor live demonstratie en bespreking van de oplevering
