name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Pas dit aan naar de naam van je hoofdtak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Pas dit aan naar de gewenste Ruby-versie
    
      - name: Install Ruby and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install bundler      

       - name: Clone AmuseWiki
        run: |
          git clone https://github.com/melmothx/amusewiki.git
          cd amusewiki
          bundle install
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake assets:precompile
          bundle exec rails server -b 0.0.0.0


      - name: Wait for AmuseWiki to Start
        run: sleep 10  # Wacht een paar seconden om ervoor te zorgen dat de server is gestart

      - name: Test AmuseWiki
        run: |
         curl http://localhost:3000
