name: Check Workflow

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Greet
        run: echo "Hello, GitHub Actions!"

      - name: Show Date
        run: echo "Current date: $(date)"

      - name: List Files
        run: ls -al
